### ISSUE TITLE
Arxiv Paper Link

### ISSUE THREAD

**Issue by gogolgrind** [mravanelli/SincNet#1]
Dear Mirco,

I couldn't find the link to arxiv paper. When will it be available?

Thanks.

**Comment by mravanelli** [comment]
Hi,
I submitted the paper on arxiv yesterday. It should be available tomorrow!

Thank you for the interest in this project (the repository is not fully
ready. I will do some small changes next days).

Best,

Mirco

**Comment by mravanelli** [comment]
Hi, you can fine now the paper on Arxiv! 
http://arxiv.org/abs/1808.00158

**Comment by mravanelli** [comment]
paper added
