### ISSUE TITLE
how to make TIMIT_labels.npy file ?

### ISSUE THREAD

**Issue by eeric** [mravanelli/SincNet#12]
how to make TIMIT_labels.npy file ?

**Comment by mravanelli** [comment]
Hi!
The  TIMIT_labels.npy is a simple python dictionary that has sentence_id as
key and an integer as value. The integers (that range between 0 and
N_speakers-1) are the labels of our speaker-identification system and tell
us which is the speaker that is speaking in each utterance. The
construction of this dictionary depends on how the dataset is organized and
where the speaker-id information is stored. For TIMIT is very easy. If you
consider a certain file (e.g., TIMIT/train/dr3/fcmg0/sx72.wav, the folder
"fcmg0" is the speaker. You only have to associate "fcmg0" to a unique
integer (from 0 to N_speakers-1), which is different from that used for the
other speakers.

Mirco

**Comment by eeric** [comment]
yeh, why did you use .npy fomat?

**Comment by mravanelli** [comment]
Pickle is probably the best option, but it is possible to save/load a
dictionary also using Numpy. It has very simple save/loading function
(using np.save, np.load).

But yes, you can use any format here. What is really important is to end up
with a dictionary with the information reported above.

**Comment by eeric** [comment]
ok, thank you !

**Comment by jongli747** [comment]
@mravanelli How you generate this .npy file. I have a dataset similar to TIMIT but I can't figure out how to generate .npy file like this one.
