### ISSUE TITLE
Is sincnet possible to convert back to original wave?

### ISSUE THREAD

**Issue by r06944010** [mravanelli/SincNet#16]
After using first CNN layer (sincnet) to process the waveform , is it possible to convert the feature extracted back to the original waveform ? Thanks

**Comment by mravanelli** [comment]
The current version is designed for classification rather than for generation purposes. I'm actually thinking some possible ways to use the "SincNet" idea to generate  an audio waveform with fewer parameters, but so far I don't have results on that...

**Comment by mravanelli** [comment]
In you case, you can try to add an autoencoder that should be able to recover an approximated waveform from the hidden representations...

**Comment by r06944010** [comment]
Thank you very much!
