### ISSUE TITLE
Reproducing LibriSpeech results

### ISSUE THREAD

**Issue by seandickert** [mravanelli/SincNet#17]
Hi,

I've been able to reproduce to a very close degree the results of the TIMIT experiment. However, I believe to reproduce the LibriSpeech results, I'll need a bit more information if you don't mind. I've currently downloaded the clean 100 and 360 hour datasets as well as the 500 hour "other" dataset. This has about 100 fewer speakers than the number you reference in your paper. Could you provide the names of the Libri datasets from which you drew your speakers?

How did you preprocess them? I know in the paper you mention using only 12-15s for training. Did you just taking the first 15s of each utterance (or less if the utterance was shorter)?  If not, could you explain how you arrived at the training utterances as well as the preprocessing you've done?

Could you also provide the training/testing data lists similar to TIMIT_train.scp and TIMIT_test.scp?

Again, this is aimed at trying to reproduce the Libri results, so as much specificity as possible would be great!

Thanks for all you've done!

**Comment by mravanelli** [comment]
Sure, upon request we can share the Librispeech version that we used for training/testing of SincNet speaker-id. You can find it here:
https://drive.google.com/drive/folders/1lDHRUIWzZDg_0fauo3zh4VA8LgqkwsLJ?usp=sharing

**Comment by seandickert** [comment]
Thanks for this, starting to try and reproduce them now!

**Comment by prashanth470** [comment]
Hi,

Can you also please share the code for pre-processing Librispeech data?

Thank you!

**Comment by mravanelli** [comment]
If you want,
you can directly download the sub-set of librispeech data used in our study
from here:

https://drive.google.com/open?id=1lDHRUIWzZDg_0fauo3zh4VA8LgqkwsLJ

Best,

Mirco
