### ISSUE TITLE
Improving SincNet results on TIMIT by adding reverberation

### ISSUE THREAD

**Issue by seandickert** [mravanelli/SincNet#18]
Not an issue, but just wanted to post that you can further decrease the sentence classification error by reverberating each training call and including them in the training dataset (effectively doubling the training size). The error drops to 0%.  I will try with Libri as well

**Comment by mravanelli** [comment]
Interesting...

**Comment by mingewang** [comment]
Oh , cool, just wondering how to doreverberation? Any Python lib? Thanks

**Comment by seandickert** [comment]
Mr Ravanelli (author of the paper and this repo) has another repo which will convolve a signal w/ an impulse response. There are also a few IR files in that repo. I used #1. Repo: https://github.com/mravanelli/pySpeechRev

**Comment by mingewang** [comment]
@seandickert , Thanks!
BTW, do you see the similar result in libri data? have you tried real audio data?

**Comment by hdubey** [comment]
@seandickert When do you perform reverberation, after reading the file chunk or do it during data processing stage? Can you share you code snippet. I guess TIMIT results were already good, 0% is FER or Sentence error rate ? Did you tried adding noise as well. Thanks!
