### ISSUE TITLE
did it had mutual Information to the open code?

### ISSUE THREAD

**Issue by eeric** [mravanelli/SincNet#19]
as described above

**Comment by mravanelli** [comment]
Sure, but It will be finally included in the pytorch-kaldi project (
https://github.com/mravanelli/pytorch-kaldi). We are working these days on
a new version of this toolkit that can also support speaker-id and
unsupervised learning. It will probably be available after the interspeech
deadline..

Mirco

**Comment by eeric** [comment]
oh, but pytorch-kaldi was complicated, i hoped you added to mutual Information in SincNet code,thank you first.

**Comment by mravanelli** [comment]
We will add it into pytorch-kaldi but of course with a clear documentation
that will help everyone to easily run an experiment...
