### ISSUE TITLE
is it possible for passes x-vectors into sincnet and classifying a speaker. like speaker verification.? 

### ISSUE THREAD

**Issue by MuruganR96** [mravanelli/SincNet#21]
@mravanelli sir. is it possible for for each speakers x-vectors pass into sincnet and classifying a speaker. like speaker verification.? 
i have my speakers x-vector embeddings (generated by kaldi benchmarked pretrained model). how can i apply speaker verification task for that using sincnet.
i am beginner for this one. i don't know how to do this?
sir any idea or suggestions.
Thank sir.

**Comment by mravanelli** [comment]
Hi,
if you want SincNet can be used to compute the x-vectors itself. You just
have to use a SincNet layer at the beginning and then use the embedding
network described in the x-vector paper. You can also try to combine the
x-vectors that you have computed with the standard SincNet architecture. An
idea could be to inject the x-vectors in some intermediate hidden layer.

Mirco

**Comment by MuruganR96** [comment]
Thank you so much sir. But TIMIT, Libri speech datasets vs Call home
datasets which one better for us?
I don't have Call Home datasets but benchmarked pretrained models
available. So sir our sincnet will produces well results equal to x-vector
embeddings call home model.

Which way is efficient for me sir. I am little more curious about our
Sincnet so.

Thank you for your kindness reply sir.
