### ISSUE TITLE
Run TIMIT data preparation.

### ISSUE THREAD

**Issue by maomaoqiuqiu** [mravanelli/SincNet#22]
Hello,When I was doing this step, the following problem occurred:
$ python TIMIT_preparation.py $TIMIT_FOLDER $OUTPUT_FOLDER data_lists/TIMIT_all.scp
Traceback (most recent call last):
  File "TIMIT_preparation.py", line 41, in <module>
    out_folder=sys.argv[2]
IndexError: list index out of range

I hope you can give me some answers, thank you very much.

**Comment by mravanelli** [comment]
*Hi,*
*you have to replace TIMIT_FOLDER and $OUTPUT_FOLDER with the right paths.*

**Comment by maomaoqiuqiu** [comment]
Hi,I already replace TIMIT_FOLDER and $OUTPUT_FOLDER with the right paths.And I have also converted to a .wav file.But the following problem occurred:
$ python TIMIT_preparation.py /home/oem/kaldi-trunk/egs/timit/data  /home/oem/SincNet/timit data_lists/TIMIT_all.scp
Traceback (most recent call last):
  File "TIMIT_preparation.py", line 75, in <module>
    sf.write(file_out, signal, fs)
  File "/home/oem/anaconda3/lib/python3.6/site-packages/soundfile.py", line 315, in write
    subtype, endian, format, closefd) as f:
  File "/home/oem/anaconda3/lib/python3.6/site-packages/soundfile.py", line 627, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/home/oem/anaconda3/lib/python3.6/site-packages/soundfile.py", line 1182, in _open
    "Error opening {0!r}: ".format(self.name))
  File "/home/oem/anaconda3/lib/python3.6/site-packages/soundfile.py", line 1355, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening '/home/oem/SincNet/timit/train/dr1/fcjf0/si1027.wav': System error.

**Comment by mravanelli** [comment]
seems a writing problem. You can check if the folder where you are writing
exists...

**Comment by maomaoqiuqiu** [comment]
Everything is working fine,thanks！！

**Comment by maomaoqiuqiu** [comment]
Hello, I have made the labels.npy and .scp file with my own data, and then the following problems occurred during the data preparation :
oem@oem-G3-3579:~/SincNet-master$ python emodb_preparation.py /home/oem/kaldi-trunk/egs/emodb/data /home/oem/SincNet-master/emodb/data data_lists/emodb_all.scp
Traceback (most recent call last):
  File "emodb_preparation.py", line 64, in <module>
    wrd_sig=ReadList(wrd_file)
  File "emodb_preparation.py", line 23, in ReadList
    f=open(list_file,"r")
FileNotFoundError: [Errno 2] No such file or directory: '/home/oem/kaldi-trunk/egs/emodb/data/train/03/03a01Fa.wrd'

**Comment by mravanelli** [comment]
The file wrd are files of the TIMIT dataset that are used in my original
data preparation code to remove initial and final silences. It's likely
that your dataset doesn't have this information. If your signals don't have
long initial and final silences you can remove the following part of the
data preparation:
 # Read wrd file
 wrd_file=wav_file.replace(".wav",".wrd")
 wrd_sig=ReadList(wrd_file)
 beg_sig=int(wrd_sig[0].split(' ')[0])
 end_sig=int(wrd_sig[-1].split(' ')[1])

 # Remove silences
 signal=signal[beg_sig:end_sig]

**Comment by Soar-Sir** [comment]
> Everything is working fine,thanks！

> Hi,I already replace TIMIT_FOLDER and $OUTPUT_FOLDER with the right paths.And I have also converted to a .wav file.But the following problem occurred:
> $ python TIMIT_preparation.py /home/oem/kaldi-trunk/egs/timit/data /home/oem/SincNet/timit data_lists/TIMIT_all.scp
> Traceback (most recent call last):
> File "TIMIT_preparation.py", line 75, in
> sf.write(file_out, signal, fs)
> File "/home/oem/anaconda3/lib/python3.6/site-packages/soundfile.py", line 315, in write
> subtype, endian, format, closefd) as f:
> File "/home/oem/anaconda3/lib/python3.6/site-packages/soundfile.py", line 627, in **init**
> self._file = self._open(file, mode_int, closefd)
> File "/home/oem/anaconda3/lib/python3.6/site-packages/soundfile.py", line 1182, in _open
> "Error opening {0!r}: ".format(self.name))
> File "/home/oem/anaconda3/lib/python3.6/site-packages/soundfile.py", line 1355, in _error_check
> raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
> RuntimeError: Error opening '/home/oem/SincNet/timit/train/dr1/fcjf0/si1027.wav': System error.

Hello~ I aslo meet the same problem, can u tell me how to solve it?

**Comment by zohrehansari** [comment]
Hi. I have run the code on TIMIT with no problem. However, when I wanted to test this code on another speech database, I faced with the following error:

File "TIMIT_preparation.py", line 59, in <module>
    [signal, fs] = sf.read(wav_file)
  File "C:\ProgramData\Anaconda3\lib\site-packages\soundfile.py", line 372, in read
    with SoundFile(file, 'r', samplerate, channels,
  File "C:\ProgramData\Anaconda3\lib\site-packages\soundfile.py", line 740, in _init_
    self._file = self._open(file, mode_int, closefd)
  File "C:\ProgramData\Anaconda3\lib\site-packages\soundfile.py", line 1264, in _open
    _error_check(_snd.sf_error(file_ptr),
  File "C:\ProgramData\Anaconda3\lib\site-packages\soundfile.py", line 1455, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening 'FARSDAT/S11.WAV': System error.

Would you please help me, how can I fix the problem?

**Comment by AnikIslam1** [comment]
Hi can someone tell me how should I replace TIMIT_FOLDER and $OUTPUT_FOLDER with the right paths or what exactly should i replace.
TIA

**Comment by AnikIslam1** [comment]
Traceback (most recent call last):
  File "speaker_id.py", line 173, in <module>
    lab_dict=np.load(class_dict_file).item()
  File "C:\Users\anika\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\numpy\lib\npyio.py", line 439, in load
    return format.read_array(fid, allow_pickle=allow_pickle,
  File "C:\Users\anika\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\numpy\lib\format.py", line 727, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False

Can someone help me about this error ?

**Comment by NAYTUN53** [comment]
> 

Can you tell me please how do you solve this error? I'm also encountering such error.

**Comment by NAYTUN53** [comment]
Can anyone tell me please how can i solve below error?

raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening 'OUTPUT_FOLDER/train/dr1/fcjf0/si1027.wav': System error.
