### ISSUE TITLE
Can SincNet be used for speech emotion recognition?

### ISSUE THREAD

**Issue by maomaoqiuqiu** [mravanelli/SincNet#28]

**Comment by maomaoqiuqiu** [comment]
Hello,I have used my own data training to generate the model_raw.pkl model. How can I apply it to speech emotion recognition?

**Comment by mravanelli** [comment]
SincNet is an architecture from processing raw audio samples and can be
thus used for emotion recognition as well. To apply to emotion recognition,
you have to use the same code, but with different labels (now available in
*TIMIT_labels.npy*  ).

Mirco

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by maomaoqiuqiu** [comment]
How do I make labels.npy for my data set?

**Comment by mravanelli** [comment]
if you take a look into labels.npy you can see that it is simply a python
dictionary where keys are the sentence-id and values are numbers between 0
and N_classes. You should create a dictionary for your dataset and your
task of interest (you can see online how to create a python dictionary).
