### ISSUE TITLE
how to download pretrained model??

### ISSUE THREAD

**Issue by mrazimi** [mravanelli/SincNet#31]
How to download the used model_raw.pkl
SincNet/exp/SincNet_TIMIT/model_raw.pkl ??

**Comment by mravanelli** [comment]
Are not available yet, but I can make them available in the next days.

Mirco

**Comment by mravanelli** [comment]
Within this external repository (https://bitbucket.org/mravanelli/sincnet_models) you can find the TIMIT parameters. Librispeech one wil be available soon!

**Comment by ggsonic** [comment]
when will librispeech one be available? I want to give the model a test. it's hard to train librispeech model.

**Comment by mravanelli** [comment]
Hi,
we are not releasing model in pytorch-kaldi, but we will do in in the
SpeechBrain project.
If anyone has a full librispeech model, I would encourage to share it!

Best,

Mirco
