### ISSUE TITLE
Installation Update

### ISSUE THREAD

**Issue by gerardgilliland** [mravanelli/SincNet#40]
As promised -- an update 

Moved from https://github.com/mravanelli/pytorch-kaldi/issues/88 to here at SyncNet
On pytorch-kaldi #88: I stated:
I am going to attempt to run the SyncNet speaker id experiment.
If it fails to run I will look into more hardware. So ...

**Attempt to install on Raspberry Pi 3B+**

Requirements:
Linux
Python 3.6/2.7 
pytorch 1.0
pysoundfile
anaconda 

Bottom line toward Requirements: 
(I am skipping the installation output except for the last line)

Linux: Raspbian GNU/Linux 9 (stretch) *** YES ***

Python 3.6/2.7 *** NO *** I have Python 3.5.3 -- Anaconda installed 3.4

pi@raspberrypi:~ $ conda install anaconda-client
Anaconda *** Maybe *** The following NEW packages will be INSTALLED:
    anaconda-client: 1.0.2-py34_0 
    clyent:          0.4.0-py34_0 
    freetype:        2.5.2-2      
    jpeg:            8d-0         
    libpng:          1.6.17-0     
    libtiff:         4.0.2-1      
    pillow:          2.9.0-py34_0 
    pip:             7.1.2-py34_0 
    python-dateutil: 2.4.2-py34_0 
    pytz:            2015.4-py34_0
    setuptools:      18.1-py34_0  
    six:             1.9.0-py34_0 
    wheel:           0.24.0-py34_0

pi@raspberrypi:~ $ sudo apt-get install pytorch
pytorch E: Unable to locate package pytorch
pi@raspberrypi:~ $ pip3 install pytorch
  Exception: You tried to install "pytorch". The package named for PyTorch is "torch"
pi@raspberrypi:~ $ sudo apt-get install torch
    RuntimeError: PyTorch does not currently provide packages for PyPI (see status at https://github.com/pytorch/pytorch/issues/566).
    Please follow the instructions at http://pytorch.org/ to install with miniconda instead.
pi@raspberrypi:~ $ conda install pytorch=0.4.1 -c pytorch
pytorch *** NO *** Error: No packages found in current linux-armv7l channels matching: pytorch 0.4.1*

pysoundfile ( conda install -c conda-forge pysoundfile)
pi@raspberrypi:~ $ conda install -c conda-forge pysoundfile
Fetching package metadata: ......
Solving package specifications: 
Error: Could not find some dependencies for pysoundfile: cffi
pi@raspberrypi:~ $ conda install --channel https://conda.anaconda.org/poppy-project cffi
The following packages conflict with each other:
  cffi
  python 3.4*
pysoundfile *** NO ***

Toward Requirements: 1.5 out of 5

************************* PLAN B *************************

**Order a new system**

https://developer.nvidia.com/embedded/buy/jetson-nano-devkit $99
NVIDIA® Jetson Nano™ Developer Kit is a small, powerful computer that lets you run multiple neural networks in parallel for applications like image classification, object detection, segmentation, and speech processing. 
JetPack is compatible with NVIDIA’s world-leading AI platform for training and deploying AI software, and reduces complexity and effort for developers by supporting many popular AI frameworks, like TensorFlow, PyTorch, Caffe, and MXNet. It also includes a full desktop Linux environment and out-of-the-box support for a variety of popular peripherals, add-ons, and ready-to-use projects.

Technical Specifications
GPU 	128-core Maxwell
CPU 	Quad-core ARM A57 @ 1.43 GHz
Memory 	4 GB 64-bit LPDDR4 25.6 GB/s
Storage 	microSD (not included)
Video Encode 	4K @ 30 | 4x 1080p @ 30 | 9x 720p @ 30 (H.264/H.265)
Video Decode 	4K @ 60 | 2x 4K @ 30 | 8x 1080p @ 30 | 18x 720p @ 30 (H.264/H.265)
Camera 	1x MIPI CSI-2 DPHY lanes
Connectivity 	Gigabit Ethernet, M.2 Key E
Display 	HDMI 2.0 and eDP 1.4
USB 	4x USB 3.0, USB 2.0 Micro-B
Others 	GPIO, I2C, I2S, SPI, UART
Mechanical 	100 mm x 80 mm x 29 mm 

https://www.adafruit.com/product/1995 $8
5V 2.4A Switching Power Supply 

https://www.sandisk.com/home/memory-cards
SanDisk microSDHC™ 64GB SD Card $13

Existing USB Keyboard, USB Mouse, HDMI screen

Toward Requirements: 
Linux: Ubuntu 18.04 LTS
Python 3.6
PyTorch 1.1

Watched a tutorial on configuring, booting up, and running some examples.
And another on Introduction to Deep Learning

Unknown out of 5 (I will update you in a week / 10 days)

**Comment by TParcollet** [comment]
I have no idea on how Jetson will behave with Kaldi tough.

**Comment by gerardgilliland** [comment]
@TParcollet,
Thank you for your perspective.  I suspect 'tough' (hard) is 'though' (although).
The Jetson Nano probably is under powered. It may not do Kaldi. 
Realistically, I might not be able to do Kaldi.
But for $99, I see it as a good educational tool.
At least the documentation describes neural networks and uses PyTorch.
I will see how far I get with the SyncNet speaker id experiment.
