### ISSUE TITLE
TIMIT (.wrd, .txt, .phn) file interpretations (numbers in front of the line)

### ISSUE THREAD

**Issue by andriuslauraitis** [mravanelli/SincNet#42]
Hello,

I want to find out more details about TIMIT database (in particular .TXT, .PHN and .WRD files):
For example (in folder train/dr1/FCJF0). 

File SI1657.TXT i have the following:
 0 45466 Or borrow some money from someone and go home by bus?

Question: What does numbers '0' and '45466' refer to?  Perhaps time duration in miliseconds?

File SI1657.WRD : 
2120 3533 or
3533 8200 borrow
8200 12291 some
12291 15325 money
15325 18435 from
18435 25984 someone
25984 28960 and
28960 31000 go
31000 34599 home
34599 36200 by
36200 43480 bus

Question: What does numbers (in first two columns) refer to? 

File SI1657.PHN  (took a fragment) : 
0 2120 h#
2120 2725 q

Question: What does numbers (0, 2120 and 2120, 2725) refer to? 

Another question: Would SincNet work if no .phn (phonetics) files are provided to the dataset?

Best regards,
Andrius L.

**Comment by mravanelli** [comment]
Those files contains labels in term of sentence (.txt), words (.wrd), and
phonemes (.phn).
The first number in the column ins the starting sample, the second is the
end one.
In this repository, SincNet is used for speaker-identification and the only
label we use is the speaker identity (e.g., "FCJF0").

Best,

Mirco

**Comment by andriuslauraitis** [comment]
Starting sample meaning "in which second (milisecond)" the particular word was started to be spoken? (if taking into account the whole speaking length (duration))? 
So, if once again taking the file: "File SI1657.WRD", we can say that the word 'borrow' was spoken from  
time 3533 to time 8200 (miliseconds)? 

Perhaps, when i prepare my own data for SincNet i don't need to specify these 2 numbers at all? But i noticed that in file 'TIMIT_preparation.py' there is a reading from .wrd file:  wrd_file=wav_file.replace(".wav",".wrd")

Best,
Andrius L.

**Comment by mravanelli** [comment]
they are not milliseconds, they are samples (e.g., from sample number 3533
to sample number 8200). In our case, the wrd file is only used to remove
the silences and the beginning and at the end of each sentence.

**Comment by andriuslauraitis** [comment]
Ok. So, is there a reference somewhere in TIMIT corpus to these sample numbers? Or these sample numbers ar calulated automatically (in some way) for the audio file.

Best,
Andrius L.
