### ISSUE TITLE
TIMIT_preparation.py

### ISSUE THREAD

**Issue by harishmalaiappan** [mravanelli/SincNet#43]
File "/home/administrator/Videos/SincNet-master/TIMIT_preparation.py", line 51, in <module>
    copy_folder(in_folder,out_folder)
  File "/home/administrator/Videos/SincNet-master/TIMIT_preparation.py", line 36, in copy_folder
    shutil.copytree(in_folder, out_folder, ignore=ig_f)
  File "/home/administrator/Music/dell/lib/python3.5/shutil.py", line 303, in copytree
    names = os.listdir(src)
NotADirectoryError: [Errno 20] Not a directory: '/home/administrator/Videos/SincNet-master/TIMIT_preparation.py'

need solution for the above mentioned error...

**Comment by mravanelli** [comment]
Hi,
I think it is just a path problem. Try to make sure that
"'/home/administrator/Videos/SincNet-master/" actually exists.

Mirco

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
