### ISSUE TITLE
error in create_batches

### ISSUE THREAD

**Issue by oualido1212** [mravanelli/SincNet#45]
Hi,
First of all, thanks for sharing your work :)

i use google colab to excute this project

 when i run ''!python3 "/content/keras-sincnet/speaker_id.py" --cfg=/content/keras-sincnet/cfg/SincNet_TIMIT.cfg''

 I get the following error:

 File "/content/keras-sincnet/speaker_id.py", line 227, in <module>
    [inp,lab]=create_batches_rnd(batch_size,data_folder,wav_lst_tr,snt_tr,wlen,lab_dict,0.2)
  File "/content/keras-sincnet/speaker_id.py", line 53, in create_batches_rnd
    lab_batch[i]=lab_dict[wav_lst[snt_id_arr[i]]]
KeyError: 'TRAIN/DR1/FSJK1/SX305.WAV'

Can you give some guidelines about how to resolve this error

**Comment by mravanelli** [comment]
Hi,
thank you for your interest in my research!
The current code supports lowecase names (e.g., sx35/sa1.wav rather than
SX35/SA1.WAV). You can either change the names or modify the code to
support uppercase names. You can take a look into the past issues of the
repo where other users had the same issue.

Best,

Mirco

**Comment by oualido1212** [comment]
thanks sir the code run correctly 
Now I wanted to use the trained model to make test ''speaker idendification and prediction with wav files li. How do I get the prediction? Can you please help?

Thanks!

**Comment by mravanelli** [comment]
Hi,
Do you mean how you can access the vector that contains the predictions
done by the DNN?

Mirco

**Comment by oualido1212** [comment]
ahow would I get the predicted speaker for the TIMIT wavefile ''exemple :dr1/fjlr0/sa1.wav'' from your SincNet implementation?

**Comment by mravanelli** [comment]
The variable "pred" (see line 230 in speaker_id.py) contains the id of the
predicted speaker.

Mirco
