### ISSUE TITLE
training on new datset

### ISSUE THREAD

**Issue by Aki58** [mravanelli/SincNet#46]
while running speaker id on my dataset I am getting the following error

```python
Traceback (most recent call last):
  File "speaker_id.py", line 227, in <module>
    [inp,lab]=create_batches_rnd(batch_size,data_folder,wav_lst_tr,snt_tr,wlen,lab_dict,0.2)
  File "speaker_id.py", line 52, in create_batches_rnd
    sig_batch[i,:]=signal[snt_beg:snt_end]*rand_amp_arr[i]
ValueError: could not broadcast input array from shape (3200,2) into shape (3200)
```

**Comment by mravanelli** [comment]
Hi,
which kind of datasets you are using? It seems there are two channels into
the input audio...

**Comment by Aki58** [comment]
yes, the audio sample had 2 channels, can you please elaborate the type audio files used like frame rate and sampling frequency, etc. and what effects the model quality.

**Comment by mravanelli** [comment]
The network expects single channel inputs (to fix it, just select one of
the two channels).  The code should work with any sampling frequency
(please, set the field "fs" in the config file according). Our experiments
have been done with fs=16000.

**Comment by Aki58** [comment]
In my experiment, the sound quality is a bit poor with sampling frequency 8000 and I am going to use mono channel audios. Any idea of how sincnet will perform in this case and what are the best practices I should follow. And i don't have samples written in a wrd file so what all preprocessing steps are needed. 

Thanks!!

**Comment by mravanelli** [comment]
the sampling frequency of 8 kHz (telephone quality) shouldn't be that bad.
Most of the speaker-id information lies in the lower part of the spectrum...

**Comment by Aki58** [comment]
Thanks, and how can i remove silence without having the wrd file. As Currently i am using pydub.

**Comment by mravanelli** [comment]
You can try to use a simple energy-based VAD...

**Comment by Aki58** [comment]
Thanks for suggesting energy based VAD will it be good like the way you are removing silence and one more query since the training data required is between 12-15s so If the length of audio file per user is variable then how the model will perform like some users with 14s audio and some with 20s audio combined.

**Comment by mravanelli** [comment]
In general, more data are better. It could be better to avoid having too
much data from one speaker and too little data from another one, but 14s
and 20s should not be a big problem!

**Comment by Aki58** [comment]
Thanks, I have trained the model successfully with good results. Closing the issue and i also want to know what should be the approach for doing the same in other languages.
