### ISSUE TITLE
How to do the GPU parallel with this code?

### ISSUE THREAD

**Issue by 15522056966** [mravanelli/SincNet#51]
Hello,

I can succeed in running this code with only one gpu. But I failed when I tried to use DataParallel to
call several gpus. How can I use several gpus to faster the training process?

Main code is listed:

CNN_net=CNN(CNN_arch)
CNN_net.cuda()
CNN_net=nn.DataParallel(CNN_net)

DNN1_net=MLP(DNN1_arch)
DNN1_net.cuda()
DNN1_net=nn.DataParallel(DNN1_net)

DNN2_net=MLP(DNN2_arch)
DNN2_net.cuda()
DNN2_net=nn.DataParallel(DNN2_net)

The error info like this:

Traceback (most recent call last):
  File "speaker_id.py", line 180, in <module>
    DNN1_arch = {'input_dim': CNN_net.out_dim,
  File "/Work19/2017/xxx/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 535, in __getattr__
    type(self).__name__, name))
AttributeError: 'DataParallel' object has no attribute 'out_dim'

**Comment by hamiGH** [comment]
You should create a new class with these layers:

class MyModel(nn.Module):

    def __init__(self, options):
        super(MyModel, self).__init__()
        //parse config file
        ...
         Feature extractor CNN
        CNN_arch = {'input_dim': wlen,
                    'fs': fs,
                    'cnn_N_filt': cnn_N_filt,
                    'cnn_len_filt': cnn_len_filt,
                    'cnn_max_pool_len': cnn_max_pool_len,
                    'cnn_use_laynorm_inp': cnn_use_laynorm_inp,
                    'cnn_use_batchnorm_inp': cnn_use_batchnorm_inp,
                    'cnn_use_laynorm': cnn_use_laynorm,
                    'cnn_use_batchnorm': cnn_use_batchnorm,
                    'cnn_act': cnn_act,
                    'cnn_drop': cnn_drop,
                    }

        self.CNN_net = CNN(CNN_arch)
        # self.CNN_net.cuda()


        DNN1_arch = {'input_dim': self.CNN_net.out_dim,
                     'fc_lay': fc_lay,
                     'fc_drop': fc_drop,
                     'fc_use_batchnorm': fc_use_batchnorm,
                     'fc_use_laynorm': fc_use_laynorm,
                     'fc_use_laynorm_inp': fc_use_laynorm_inp,
                     'fc_use_batchnorm_inp': fc_use_batchnorm_inp,
                     'fc_act': fc_act,
                     }

        self.DNN1_net = MLP(DNN1_arch)
        # self.DNN1_net.cuda()

        DNN2_arch = {'input_dim': fc_lay[-1],
                     'fc_lay': class_lay,
                     'fc_drop': class_drop,
                     'fc_use_batchnorm': class_use_batchnorm,
                     'fc_use_laynorm': class_use_laynorm,
                     'fc_use_laynorm_inp': class_use_laynorm_inp,
                     'fc_use_batchnorm_inp': class_use_batchnorm_inp,
                     'fc_act': class_act,
                     }

        self.DNN2_net = MLP(DNN2_arch)
       
        **modules = [
            self.CNN_net,
            self.DNN1_net,
            self.DNN2_net
        ]**

        **self.net = nn.ModuleList(modules)**


    def train(self):
        self.CNN_net.train()
        self.DNN1_net.train()
        self.DNN2_net.train()


    def forward(self, inp):
        # out = self.DNN2_net(self.DNN1_net(self.CNN_net(inp)))
        for i, n in enumerate(self.net):
            inp = n(inp)
        return inp
---------------------------------------------------------------------
options=read_conf("cfg/SincNet_Librispeech.cfg")

model = MyModel(options)

model.train()

parallel_model = DataParallel(model, device_ids=[0, 1])
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
parallel_model.to(device)

**Comment by 15522056966** [comment]
> You should create a new class with these layers:
> 
> class MyModel(nn.Module):
> 
> ```
> def __init__(self, options):
>     super(MyModel, self).__init__()
>     //parse config file
>     ...
>      Feature extractor CNN
>     CNN_arch = {'input_dim': wlen,
>                 'fs': fs,
>                 'cnn_N_filt': cnn_N_filt,
>                 'cnn_len_filt': cnn_len_filt,
>                 'cnn_max_pool_len': cnn_max_pool_len,
>                 'cnn_use_laynorm_inp': cnn_use_laynorm_inp,
>                 'cnn_use_batchnorm_inp': cnn_use_batchnorm_inp,
>                 'cnn_use_laynorm': cnn_use_laynorm,
>                 'cnn_use_batchnorm': cnn_use_batchnorm,
>                 'cnn_act': cnn_act,
>                 'cnn_drop': cnn_drop,
>                 }
> 
>     self.CNN_net = CNN(CNN_arch)
>     # self.CNN_net.cuda()
> 
> 
>     DNN1_arch = {'input_dim': self.CNN_net.out_dim,
>                  'fc_lay': fc_lay,
>                  'fc_drop': fc_drop,
>                  'fc_use_batchnorm': fc_use_batchnorm,
>                  'fc_use_laynorm': fc_use_laynorm,
>                  'fc_use_laynorm_inp': fc_use_laynorm_inp,
>                  'fc_use_batchnorm_inp': fc_use_batchnorm_inp,
>                  'fc_act': fc_act,
>                  }
> 
>     self.DNN1_net = MLP(DNN1_arch)
>     # self.DNN1_net.cuda()
> 
>     DNN2_arch = {'input_dim': fc_lay[-1],
>                  'fc_lay': class_lay,
>                  'fc_drop': class_drop,
>                  'fc_use_batchnorm': class_use_batchnorm,
>                  'fc_use_laynorm': class_use_laynorm,
>                  'fc_use_laynorm_inp': class_use_laynorm_inp,
>                  'fc_use_batchnorm_inp': class_use_batchnorm_inp,
>                  'fc_act': class_act,
>                  }
> 
>     self.DNN2_net = MLP(DNN2_arch)
>    
>     modules = [
>         self.CNN_net,
>         self.DNN1_net,
>         self.DNN2_net
>     ]
> 
>     self.net = nn.ModuleList(modules)
> 
> 
> def train(self):
>     self.CNN_net.train()
>     self.DNN1_net.train()
>     self.DNN2_net.train()
> 
> 
> def forward(self, inp):
>     # out = self.DNN2_net(self.DNN1_net(self.CNN_net(inp)))
>     for i, n in enumerate(self.net):
>         inp = n(inp)
>     return inp
> ```
> 
> options=read_conf("cfg/SincNet_Librispeech.cfg")
> 
> model = MyModel(options)
> 
> model.train()
> 
> parallel_model = DataParallel(model, device_ids=[0, 1])
> device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
> parallel_model.to(device)

Thanks, hamiGH, I will try your way later.
ps: I have temporarily realized parallel by importing tensorflow. And it seems worked.
