### ISSUE TITLE
Removing non-speech intervals

### ISSUE THREAD

**Issue by bluemonk482** [mravanelli/SincNet#55]
> Non-speech intervals at the beginning and end of each sentence were removed.

May I ask what tool or package did you use for removing the non-speech intervals please? 

Many thanks!

**Comment by mravanelli** [comment]
We use a simple VAD based on energy thresholds. You can find it here:
https://github.com/santi-pdp/pase/blob/master/prepare_segmented_dataset.py
Note that to have reasonable results you might need to tune a bit some of
the hyperparameters (e.g, en_th = 0.3).

Best,

Mirco

**Comment by bluemonk482** [comment]
Thanks very much for the quick reply @mravanelli !

Appreciated!
