### ISSUE TITLE
Problem on SER % 

### ISSUE THREAD

**Issue by Sathiyakugan** [mravanelli/SincNet#57]
Since the paper indicates that Sentence error rate, could you please explain about the Sentence error rate on Speaker Identification?

**Comment by mravanelli** [comment]
The Sentence Error Rate (SER%) is the classification error rate computed at
sentence level. In practice, we take a decision based on windows of 200 ms
shifted by 10 ms and we average the posterior probabilities over all these
frames composing the sentence. The class with the highest average
probability is the winner and it is compared with the reference ground
truth. This procedure is repeated for all the sentences of the test set.

Best,

Mirco
