### ISSUE TITLE
What's the reason of `Batch_dev = N_fr` when `avoid_small_en_fr = True`?

### ISSUE THREAD

**Issue by qwfy** [mravanelli/SincNet#61]
In `compute_d_vector.py`, when `avoid_small_en_fr = True`, `Batch_dev` is set to `N_fr`, is this necessary?

https://github.com/mravanelli/SincNet/blob/d64244991324f96d77add11dc86939a7a81ae14d/compute_d_vector.py#L184

**Comment by mravanelli** [comment]
I check the code again and probably that line shouldn't be necessary. Have
you tried to comment it out?

Best,

Mirco

**Comment by qwfy** [comment]
If commented out, an error is produced.

This is related to issue #62.

The audio that produced the error has a length of 49460 sample points, the loop at the line https://github.com/mravanelli/SincNet/blob/d64244991324f96d77add11dc86939a7a81ae14d/compute_d_vector.py#L218 produces 290 examples, (as it should be), but https://github.com/mravanelli/SincNet/blob/d64244991324f96d77add11dc86939a7a81ae14d/compute_d_vector.py#L215 only allocates 289 slots, so when handling the left over, the left side of  https://github.com/mravanelli/SincNet/blob/d64244991324f96d77add11dc86939a7a81ae14d/compute_d_vector.py#L232 would only have 33 slots instead of the correct 34 (`290 - 128 * 2`) slots.

Setting `Batch_dev = N_fr` would cause https://github.com/mravanelli/SincNet/blob/d64244991324f96d77add11dc86939a7a81ae14d/compute_d_vector.py#L230 to be never executed, thus hides the error.
