### ISSUE TITLE
pt_file error

### ISSUE THREAD

**Issue by gerardgilliland** [mravanelli/SincNet#63]
Dr. Ravanelli,
I changed pt_file in cfg and now fail. 
Do you have any recommendations or do you need more information?
Thank you and Peace,
Gerard Gilliland

In SincNet_TIMIT.cfg 
WAS:
pt_file=none
NOW:
pt_file=TIMIT_norm/test/dr6/fmgd0/si1564.wav

Traceback (most recent call last):
  File "speaker_id.py", line 207, in <module>
    checkpoint_load = torch.load(pt_file)
  File "/home/gerardg/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 387, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/gerardg/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 564, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
ValueError: could not convert string to int

In BirdSongs_SONGS.cfg
WAS:
pt_file=none
NOW:
pt_file=SONGS_norm/test/B27000/S27000_XC171727.wav

Traceback (most recent call last):
  File "bird_id.py", line 217, in <module>
    checkpoint_load = torch.load(pt_file)
  File "/home/gerardg/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 387, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/gerardg/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 564, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: unpickling stack underflow

**Comment by gerardgilliland** [comment]
It looks like the line in question needs to be:
checkpoint_load = torch.load(output_folder+'/model_raw.pkl')
it runs with the above change.
https://pytorch.org/tutorials/beginner/saving_loading_models.html
Then I think I need to do a model.eval()
Thank you,
Gerard

**Comment by mravanelli** [comment]
Hi,
thank you for the interest in my work.
The pt file must be a model file in pkl format and not a wav file as
reported in the first email.

**Comment by gerardgilliland** [comment]
Dr. Ravanelli,
Thank you for responding, correcting me, and confirming my second email.
Could you please point me to some code that loads your saved model, reads a test file, and predicts the speaker in that file?
From your documentation, I think perhaps PyTorch-Kaldi run_exp.py could be modified to handle this.
However, from looking at the code, I don’t think I could modify it to run in SincNet.
Thank you,
Gerard

**Comment by kangbojk** [comment]
pt_file=output_folder/model_raw.pkl

**Comment by gerardgilliland** [comment]
@kangbojk 
I agree. It can be the model that was saved or a backup with different parameters.
What I am requesting from @mravanelli above is after loading the model I would like the ability to read and evaluate a single test wav file, and display the speaker's name of that wav file.
Thank you. 
Gerard

**Comment by gerardgilliland** [comment]
I am closing this pt_file error. 
I was using it improperly and have been corrected by @mravanelli  and @kangbojk. 
I will open another request "predict the speaker of a file"
Thank you,
Gerard
