### ISSUE TITLE
predict the speaker of a file

### ISSUE THREAD

**Issue by gerardgilliland** [mravanelli/SincNet#65]
Dr. Ravanelli,
Could you please point me to some code that loads your saved model, reads a test file, and predicts the speaker in that file?
From your documentation, I think perhaps PyTorch-Kaldi run_exp.py could be modified to handle this. But I don’t think I am capable of modifying it to run here in SincNet.
Thank you,
Gerard

**Comment by mravanelli** [comment]
Hi Gerard,
I think this could be inferred by the script speaker_id.py (see the evaluation). In this script you also find the loading and testing parts.

**Comment by gerardgilliland** [comment]
Dr. Ravanelli,

I apologize for my poorly defined question.
I have studied and have run your speaker_id.py and my results track close to your results.
I accept you closing the issue, but I cannot infer what I am looking for.

What I am looking for, and what I will use speaker_id.py as the base for, in a speaker prediction app, is:

[WhoIsThisSpeaker.zip](https://github.com/mravanelli/SincNet/files/3653396/WhoIsThisSpeaker.zip)
(Unzip for the wav file.)

Who is This Speaker? What is the confidence level of your top three predictions.
Rank, Speaker, Confidence Level
1.	mxxx0 , 97.52 %
2.	myyy1, 2.01 %
3.	mzzz0, 0.05 %

If three speakers were at a cocktail party, I would hope for a split depending on time speaking:
1.	mxxx0 , 52.0 %
2.	myyy1, 27.0 %
3.	fzzz0, 20.5 %

Thank you,
Gerard
