### ISSUE TITLE
 Cumulative frequency response of the SincNet filters

### ISSUE THREAD

**Issue by javi-99** [mravanelli/SincNet#69]
Hi Mirco Ravanelli,
Your SincNet architecture is very interesting,  I want to know how you plotted cumulative frequency response plot using low_hz and band_hz (converging parameters in the code)? 
![filter](https://user-images.githubusercontent.com/47158235/65358431-06ea0480-dc13-11e9-94fe-cd782dd0b697.PNG)

I am waiting for your response. Thanks.

**Comment by mravanelli** [comment]
We just computed the Fourier transforms of all the learned filters and we averaged them.

**Comment by javi-99** [comment]
Thank you so much
