### ISSUE TITLE
Big data loading - time consumption

### ISSUE THREAD

**Issue by CarmiShimon** [mravanelli/SincNet#71]
Hi mravaneli, 
Thanks for your great work! I really appreciate your code sharing.
I have a question regarding batch loader - as it seems, you load .wav by .wav and it uses only 1 processor which consumes a lot of time.
Is there any parallel script that loads the data in multi-processors?
Do you recommend on doing so?

Thanks in advance,
Carmi

**Comment by mravanelli** [comment]
Hi Carmi,
thank you very much for your interest in my research. In the simple code
reported in the repository we didn't use a parallel data loader. However,
one can use to pytorch dataloader
(https://pytorch.org/docs/stable/data.html#torch.utils.data.DataLoader)
that reads all the sentences in parallel.

Best,

Mirco

**Comment by CarmiShimon** [comment]
Thanks a lot!
