### ISSUE TITLE
Any class detector

### ISSUE THREAD

**Issue by CarmiShimon** [mravanelli/SincNet#72]
Hi Mirco,

I wonder if you have in mind such an idea of recognizing "noise" or "non speech" like garbage collector which will work well for any other class instead of using VAD?

Thanks a lot,
Carmi

**Comment by mravanelli** [comment]
HI Carmi,
this is for sure possible. As far as I know some people have already used SincNet for speech activity detection (but I have to double check better). I thus thing it could make sense to add this garbage class.

**Comment by hbredin** [comment]
I've used SincNet successfully for speech activity detection, speaker change detection, and overlapped speech detection. See [this paper](https://arxiv.org/abs/1911.01255).

**Comment by CarmiShimon** [comment]
Thanks a lot!
