### ISSUE TITLE
SincConv on multiple channels

### ISSUE THREAD

**Issue by chanshing** [mravanelli/SincNet#76]
Thanks for the nice work. I was wondering why is the SincConv not implemented for multiple channels? I think this could be implemented by simply repeating the filters in the channel direction, or am I missing something? 
Related question: I am considering to apply multiple layers of SincConv -- would this make sense?

**Comment by mravanelli** [comment]
Hi,
yes it makes sense to extend SincConv to multiple channels. I'm not sure
that it makes sense to have many consecutive layers of SincConv. After the
first layer we might loose a bit the sense of what we are doing and my
feeling is that two parameters are not enough. Feel free to share the
results if you achieve something interesting with it!

Best,

Mirco
