### ISSUE TITLE
Musical instruments classification

### ISSUE THREAD

**Issue by CarmiShimon** [mravanelli/SincNet#78]
Mirco, I tried your work on VCTK, LibriSpeech and TIMIT. All databases get high accuracy and I'm very pleased.
Currently I'm trying to apply your code on another task - Musical instruments classification.
I wonder, is it too overkill for let's say 10 instruments? Are the sinc filters still needed?
In case it sounds right to you, what changes would you recommend?
I would say enlarge window 200ms->500ms, as well as overlap 10ms->50ms. 
Maybe also lesser filters (80->20)?
What would be the filters' length? Still 251?

With much appreciation for your info.
Thanks,
Carmi

**Comment by mravanelli** [comment]
Dear Carmi,
the application you propose it is very interesting.
It is however very hard to guess good values of the hyperparameters.
Usually it is better to try some of them and see what happens.
Mirco
