### ISSUE TITLE
Amplification factor

### ISSUE THREAD

**Issue by CarmiShimon** [mravanelli/SincNet#81]
Hi and thanks again for replying the issues and your great work!
I wonder: in create_batches_rnd function - rand_amp_arr could be greater then 1 after the multiplication so it could make the audio 'clipping'. 
What do you think about it?

Thanks a lot, 
Carmi

**Comment by mravanelli** [comment]
Hi,
thank you for the question. Actually, in the config file we use "
cnn_use_laynorm_inp=True" that normalizes every time the dynamic and make
rand_amp useless.
Without layer norm set to "true",  you might have signals with amplitude
>1. This is not real clipping (we are not saving the signal), but it could
be something that one wants to avoid.

Best,

Mirco

**Comment by CarmiShimon** [comment]
Thanks a lot for the detailed explanation!
Carmi
