### ISSUE TITLE
SincNet on Tensorflow?

### ISSUE THREAD

**Issue by sivagururaman** [mravanelli/SincNet#9]
@mravanelli 
Wanted to know if there is a port of the net on TF?
Regards,
Sivam

**Comment by shatealaboxiaowang** [comment]
Hi mravanelli:
      I am having some problems now, sincNet is very poorly tested on the voice of the same person but through different channels (for example, the same person's voice through pc and iphone), I don't know if you have tested this situation. How should this situation be solved? Another problem is that in the case of sound reverberation (same voice speaked by two colleagues) and large signal-to-noise ratio, the model performance is also very poor. I wonder if you have a good way to remove sound reverberation and reduce noise? I look forward to your answer and thank you very much!

**Comment by mravanelli** [comment]
Dear Wenkai,
are you able to replicate my results on the standard TIMIT dataset? This is
to exclude first any kind of implementation bug.

Mirco

**Comment by grausof** [comment]
I created this version of SincNet for keras (tensorflow) and I managed to reproduce the same results on TIMIT. I hope it goes well. 
[https://github.com/grausof/keras-sincnet](https://github.com/grausof/keras-sincnet)

**Comment by mravanelli** [comment]
Great job Francesco!

Mirco

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by dschwertfeger** [comment]
> I created this version of SincNet for keras (tensorflow) and I managed to reproduce the same results on TIMIT. I hope it goes well.
> https://github.com/grausof/keras-sincnet

@grausof where did this go?

**Comment by grausof** [comment]
> > I created this version of SincNet for keras (tensorflow) and I managed to reproduce the same results on TIMIT. I hope it goes well.
> > https://github.com/grausof/keras-sincnet
> 
> @grausof where did this go?

Try non!

**Comment by Ciel24** [comment]
@grausof 
I tried to run your code with the same tensorflow and keras version. 
But I got the following error. 
It should be noted that I changed the keras to tensorflow.keras in importing. 
I tried different ways to solve it. Do you have any idea how can I fix it? 
I really apprecaite that if you can help.
FailedPreconditionError (see above for traceback): Error while reading resource variable sinc_conv1d/Variable_102 from Container: 
localhost. This could mean that the variable was uninitialized. Not found: Resource localhost/sinc_conv1d/Variable_102/N10tensorflow3VarE does not exist.
         [[Node: sinc_conv1d/Variable_103/Initializer/ReadVariableOp = ReadVariableOp[dtype=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](sinc_conv1d/Variable_102)]]

**Comment by sebastiaanvbb** [comment]
Hello everyone,

Has anyone implemented the code yet in tensorflow 2.0?
The above error I believe I also ran into. I believe it was a version problem. Downgrade to keras =2.1.6 should solve.

regards,

**Comment by suyuzhang** [comment]
Hi @Ciel24,
Have you solved this problem?
I got the same error after I changed the keras to tensorflow.keras.

thanks,
